<a href="https://colab.research.google.com/github/Rockrs/Algorithm_DS/blob/master/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Numpy arrays

1-D array

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(5)
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
arr = np.array([1.2,2,3])
print(arr,type(arr))

[1.2 2.  3. ] <class 'numpy.ndarray'>


In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(3,)

In [ ]:
arr.size

3

In [ ]:
arr.itemsize

8

2-d Array

In [ ]:
arr2d = np.array([
                 [1,2,3],
                [4,5,6] 
])
print(arr2d,type(arr2d))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [ ]:
arr2d.size

6

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr.itemsize

8

3-d Array

In [ ]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])
print (arr3d,type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'>


In [ ]:
arr3d.shape

(2, 2, 3)

In [ ]:
arr.itemsize

8

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.size

12

Initializing numpy arrays with specifc size

In [ ]:
# Arrays with ones

np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
# Arrays with some other constant
100*np.ones((2,3,5))

array([[[100., 100., 100., 100., 100.],
        [100., 100., 100., 100., 100.],
        [100., 100., 100., 100., 100.]],

       [[100., 100., 100., 100., 100.],
        [100., 100., 100., 100., 100.],
        [100., 100., 100., 100., 100.]]])

In [ ]:
# Arrays with All zeros
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

Generating Random Numbers With Specific Distribution

In [ ]:
# Getting random nunbers that are sampled form Normal Distribution ie. they have mean=0 and variance=1
np.random.randn(2,3,4)

array([[[ 1.08465483, -2.31455364,  0.01736311, -1.18381191],
        [-0.80875523,  0.69779446,  0.29805926,  2.40156474],
        [ 0.96296009,  1.26776344, -1.75226734, -0.06395134]],

       [[ 0.34862866, -1.09524195,  0.32833844,  0.66364313],
        [-0.86330132,  0.08530584, -0.30017296, -0.31167798],
        [ 0.02891413, -0.97929239, -1.48988751,  2.56992225]]])

In [ ]:
# Getting random numbers between two integers
np.random.randint(0,10,(2,3))

array([[3, 0, 2],
       [3, 3, 9]])

In [ ]:
# Getting random numbers from Uniform Distributions and between 0-1
np.random.rand(3,2,3)

array([[[0.82946527, 0.61499261, 0.5767375 ],
        [0.5319295 , 0.83486276, 0.41737699]],

       [[0.39559681, 0.06884984, 0.98804917],
        [0.14510592, 0.32110064, 0.44090793]],

       [[0.44719745, 0.1077858 , 0.18423586],
        [0.03628731, 0.86720292, 0.94142995]]])

In [ ]:
np.arange(7,70,6) # To generate numbers between start and end with particular step size

array([ 7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67])

In [ ]:
np.linspace(7,70,6)

array([ 7. , 19.6, 32.2, 44.8, 57.4, 70. ])

Numby Array with different types

In [ ]:
np.array([True,False,True,False])
str_arr = np.array(['1.21','1.2','1.33','1.5'])
print (str_arr,type(str_arr))

convert_str_float = np.array(str_arr,dtype='float')
print(convert_str_float)

['1.21' '1.2' '1.33' '1.5'] <class 'numpy.ndarray'>
[1.21 1.2  1.33 1.5 ]


Indexing Numpy Array

In [ ]:
arr4d=np.array([[
    [[1,2,3],
    [4,5,6]
    ],
    [[7,8,9],
    [10,11,12]
        ],
    [[13,14,15],
    [16,17,18]
        ]
    ],
    
    [
    [[1,6,3],
    [4,8,3]
    ],
    [[7,8,7],
    [10,1,2]
        ],
    [[3,4,5],
    [169,179,189]
        ]
    ]])

print(arr4d.shape)
#print(arr4d[0,0,0,0])
#print(arr4d[1,1,1,1])
print (arr4d[:,1:,:,:])

(2, 3, 2, 3)
[[[[  7   8   9]
   [ 10  11  12]]

  [[ 13  14  15]
   [ 16  17  18]]]


 [[[  7   8   7]
   [ 10   1   2]]

  [[  3   4   5]
   [169 179 189]]]]


Fancy Indexing.. example to find Integers in my n-d array which are even

In [ ]:
arr4d=np.array([[
    [[1,2,3],
    [4,5,6]
    ],
    [[7,8,9],
    [10,11,12]
        ],
    [[13,14,15],
    [16,17,18]
        ]
    ],
    
    [
    [[1,6,3],
    [4,8,3]
    ],
    [[7,8,7],
    [10,1,2]
        ],
    [[3,4,5],
    [169,179,189]
        ]
    ]])

print(arr4d.size)
#arr4d %2==0
print(arr4d[arr4d % 2==0])

36
[ 2  4  6  8 10 12 14 16 18  6  4  8  8 10  2  4]


Array Slices

In [ ]:
arr4d=np.array([[
    [[1,2,3],
    [4,5,6]
    ],
    [[7,8,9],
    [10,11,12]
        ],
    [[13,14,15],
    [16,17,18]
        ]
    ],
    
    [
    [[1,6,3],
    [4,8,3]
    ],
    [[20,21,23],
    [31,32,33]
        ],
    [[3,4,5],
    [169,179,189]
        ]
    ]])

arr_slice = arr4d[:,1,:,:]
print (arr_slice)
arr_slice[0,0,0] = 100
print(arr_slice)
print (arr4d)

[[[ 7  8  9]
  [10 11 12]]

 [[20 21 23]
  [31 32 33]]]
[[[100   8   9]
  [ 10  11  12]]

 [[ 20  21  23]
  [ 31  32  33]]]
[[[[  1   2   3]
   [  4   5   6]]

  [[100   8   9]
   [ 10  11  12]]

  [[ 13  14  15]
   [ 16  17  18]]]


 [[[  1   6   3]
   [  4   8   3]]

  [[ 20  21  23]
   [ 31  32  33]]

  [[  3   4   5]
   [169 179 189]]]]


In [ ]:
arr=np.random.randint(0,10,(5,))
arr_list = [1,2,3]
print(arr[arr_list])

[9 5 3]


Operations on Arrays

In [ ]:
arr1 = np.random.rand(3,4,2)
arr2 = np.random.rand(3,4,2)
#print (arr1)
#print (arr2)

print (arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)

[[[1.08895377 0.72871232]
  [0.48883507 1.01981367]
  [1.11075287 0.75377736]
  [0.7347568  1.06188241]]

 [[1.49502937 0.80605785]
  [0.73095476 0.6078431 ]
  [1.12390694 1.16135725]
  [1.71835346 0.22244932]]

 [[0.84151472 0.40792722]
  [1.12216923 1.61154862]
  [0.05438977 1.20119379]
  [0.65736947 0.56126968]]]
[[[2.90064342e-01 5.96461603e-02]
  [5.81561646e-03 2.41569513e-01]
  [1.71059615e-01 1.33708107e-01]
  [8.47656896e-02 2.74284618e-01]]

 [[5.52732987e-01 1.61986048e-01]
  [1.29428268e-01 8.70780380e-02]
  [1.36988539e-01 2.19102380e-01]
  [7.36808080e-01 5.54057237e-03]]

 [[7.35797648e-02 2.74170151e-02]
  [2.38584588e-01 6.32784173e-01]
  [6.47514792e-04 3.47000590e-01]
  [9.43224605e-02 7.33300561e-02]]]
[[[ 1.34418124  6.7548215 ]
  [39.06372004  1.72583015]
  [ 5.01304657  0.60996216]
  [ 4.12660997  0.71770284]]

 [[ 0.81157342  1.11062982]
  [ 0.70043841  0.61378935]
  [ 7.07971855  3.89934787]
  [ 1.09026494  0.14741128]]

 [[ 7.49071022  0.26269491]
  [ 0.340407

Excercise--1 Calculate area left out of square of unit 1 when a circle or radius 1 is drawn inside it

In [ ]:
ndim = 2
npoints = 100000
points = np.random.rand(npoints,ndim)

dfo = np.zeros((npoints,1))
for i in range(npoints):
  for j in range(ndim):
    dfo[i] += points[i][j]**2
  
dfo = np.sqrt(dfo)
points_in_circle = dfo[dfo<=1]
f_points_outside_circle = (npoints-points_in_circle.size)/npoints
print (f_points_outside_circle*100)



21.521


In [ ]:
_